### ISSUE TITLE
[Bug Report] isaacsim.kit.xr.teleop.bridge extension not found - CloudXR teleoperation cannot fully function

### ISSUE THREAD

**Issue by tron-kohira** [isaac-sim/IsaacLab#5221]
### Describe the bug

Following the official CloudXR teleoperation documentation:
https://isaac-sim.github.io/IsaacLab/develop/source/how-to/cloudxr_teleoperation.html

The `isaacsim.kit.xr.teleop.bridge` extension cannot be resolved from any extension registry, preventing full CloudXR teleoperation.

```
Failed to resolve extension dependencies. Failure hints:
  * No versions of isaacsim.kit.xr.teleop.bridge that satisfies: [enable list]
    - Available packages for isaacsim.kit.xr.teleop.bridge version *: (none found)
  Synced registries:
     - kit/default         : found 0 packages (couldn't connect or empty)
     - kit/sdk             : found 0 packages (couldn't connect or empty)
     - kit/prod/default    : found 931 packages 
     - kit/prod/sdk        : found 785 packages 
```

The `kit/default` registry (pdx.s8k.io) is unreachable (TLS handshake fails). The extension is also not included in the Docker image (nvcr.io/nvidia/isaac-sim:6.0.0-dev2).

Additionally, `omni.kit.xr.system.openxr` does not expose `get_instance_proc_addr()`, which the bridge extension is supposed to polyfill (line 68-82 of session_lifecycle.py). Without the polyfill, `_acquire_kit_oxr_handles()` crashes with `AttributeError`.

### What works

- G1 simulation rendering streamed to PICO 4 Ultra Enterprise via CloudXR
- Camera view follows head movement in the headset

### What does not work

- Controller input from PICO does not reach Isaac Teleop at all (no pose tracking, no button input from headset controllers)
- `ControllerTracker update failed` repeats continuously
- `XR_ERROR_FORM_FACTOR_UNSUPPORTED: xrGetSystem(getInfo->formFactor) no matching system (given: 2, first: 1)` - Kit XR requests form factor 2 (handheld/AR) but CloudXR Monado only supports form factor 1 (HMD)

### Steps to reproduce

1. Install Isaac Sim 6.0 via pip: `pip install "isaacsim[all,extscache]==6.0.0"`
2. Install Isaac Lab (develop branch): `git clone https://github.com/isaac-sim/IsaacLab.git && cd IsaacLab && git checkout develop && ./isaaclab.sh --install`
3. Install Isaac Teleop: `pip install "isaacteleop[retargeters,ui,cloudxr]~=1.0.0" --extra-index-url https://pypi.nvidia.com`
4. Start CloudXR: `python -m isaacteleop.cloudxr --accept-eula --cloudxr-env-config=~/cloudxr_custom.env` (with `NV_CXR_ENABLE_PUSH_DEVICES=0`)
5. Launch teleop: `source ~/.cloudxr/run/cloudxr.env && ./isaaclab.sh -p scripts/environments/teleoperation/teleop_se3_agent.py --task Isaac-PickPlace-Locomanipulation-G1-Abs-v0 --visualizer kit --xr`
6. Click Start XR in the XR tab
7. Connect PICO 4 Ultra Enterprise via CloudXR.js client (AR Immersive)

### Questions

1. Is the `isaacsim.kit.xr.teleop.bridge` extension supposed to be included in the Isaac Sim 6.0 pip package or downloaded from a registry?
2. Is there a workaround to get controller input working without the bridge extension?
3. Is this expected to work with Isaac Sim 6.0 Early Developer Release, or should we wait for the GA release?

### System Info

- OS: Ubuntu 22.04
- GPU: NVIDIA RTX PRO 6000 Blackwell Workstation Edition (98GB VRAM)
- Driver: 580.126.09
- Isaac Sim: 6.0.0 (pip)
- Isaac Lab: develop branch (commit 78e765b)
- Isaac Teleop: 1.0.191
- CloudXR: 6.1.0
- VR Headset: PICO 4 Ultra Enterprise
- Python: 3.12.13

**Comment by tron-kohira** [comment]
Additional finding: In NVIDIA/IsaacTeleop#160, a bug related to `isaacsim.kit.xr.teleop.bridge` not loading OpenXR extensions was reported and fixed (Feb 2026). This confirms the bridge extension exists and works internally at NVIDIA.

The issue appears to be a distribution/packaging problem: the `kit/default` registry (`pdx.s8k.io`) where the bridge is hosted is unreachable from outside NVIDIA's network (TLS handshake fails), and the extension is not included in the Isaac Sim 6.0 pip package or Docker image.

Could you confirm how external users are expected to obtain this extension?

**Comment by jiwenc-nv** [comment]
here is the fix: https://github.com/NVIDIA/IsaacTeleop/pull/405

**Comment by tron-kohira** [comment]
Hi @jiwenc-nv, thanks for the response.

I installed isaacteleop 1.2.58rc1 which includes the changes from NVIDIA/IsaacTeleop#405. However, PR #405 only changes `requires-python` from a specific version to `>=3.10` - it doesn't appear to address the missing bridge extension.

After upgrading to 1.2.58rc1, the same `AttributeError: module 'omni.kit.xr.system.openxr' has no attribute 'get_instance_proc_addr'` still occurs, caused by the missing `isaacsim.kit.xr.teleop.bridge` extension which cannot be resolved from any accessible registry.

Could you clarify:
1. How is the `isaacsim.kit.xr.teleop.bridge` extension supposed to be distributed/installed for external users?
2. Is PR #405 sufficient on its own, or does it require a separate Isaac Sim 6.0 update that includes the bridge extension?

Thanks!

**Comment by tron-kohira** [comment]
Note: Another user has reported the same issue in #5368 with a different setup (Quest 3 + Manus gloves on Ubuntu 24.04 / RTX 5080), confirming this is not environment-specific and affects multiple external users. Cross-referencing for visibility.

**Comment by RandomOakForest** [comment]
Thanks for following up and for your patience. This will be fixed in the upcoming GA release. For the current `v3.0.0-beta`, the team points out that you will need to follow *one* of these 2 ways to pull the extension.

## Pulling `isaacsim.kit.xr.teleop.bridge` (or any newly-published Kit extension) into your Isaac Sim build

The extension was published to the public registry but not as a pip wheel, so you need to fetch it yourself. Two paths depending on how you installed Isaac Sim:

#### Path 1. Source build (e.g. cloned `IsaacSim` repo):

1. Open `source/apps/isaacsim.exp.extscache.kit` (or whichever experience file you launch).
2. Under `[dependencies]`, add:
```
   "isaacsim.kit.xr.teleop.bridge" = {}
```
3. Run ./build.sh from the repo root.
The build's dependency resolver will pull the extension from the public registry into `_build/<platform>/release/extscache/`, and it'll be available the next time you launch.

#### Path 2. Pip install:

1. Launch Isaac Sim.
2. Open `Window → Extensions`.
3. Search for `isaacsim.kit.xr.teleop.bridge`.
4. Click Install, then toggle **Enable**.
Kit fetches it from the registry into your local `extscache/` on the spot — no rebuild needed.
If the extension doesn't show up in the manager, check that the public Kit registry is in your registry list under the `*hamburger menu* → Settings → Extension Registries`, and refresh.

Since the GA release is just around the corner, I'll close this issue for now. Let us know if we can be of further help.
